name: CI-CD PHP Check

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PHP syntax
        run: |
          for file in *.php; do
            php -l $file || exit 1
          done

      - name: Start PHP built-in server
        run: php -S localhost:8000 &
        env:
         CI: true


      - name: Health check
        run: curl http://localhost:8000/login.php

